project_id = "fejocgswxpxtrtwknxms"

[functions.send-contact-message]
verify_jwt = false

[functions.get-entitlement]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-invite-payment]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.get-localized-price]
verify_jwt = false
